@extends('layouts.app')

@section('title', 'Sudoku')

@push('styles')
<style>
    .game-wrapper {
        display: flex;
        flex-direction: column;
        align-items: center;
        padding: 2rem 0;
        font-family: var(--font-sans, system-ui, sans-serif);
    }
    
    .sudoku-container {
        background-color: var(--card-bg, #fff);
        border: 1px solid var(--border-color);
        border-radius: 12px;
        box-shadow: 0 4px 6px rgba(0,0,0,0.1);
        padding: 2rem;
        max-width: 500px;
        width: 100%;
        text-align: center;
    }

    .level-selector {
        display: flex;
        gap: 1rem;
        justify-content: center;
        margin-bottom: 2rem;
    }

    .level-btn {
        padding: 0.5rem 1rem;
        border: 1px solid var(--border-color);
        border-radius: 8px;
        background: var(--card-bg);
        color: var(--text-color);
        cursor: pointer;
        transition: all 0.2s;
        font-weight: 500;
    }

    .level-btn:hover {
        background: var(--card-banner-bg);
    }

    .level-btn.active {
        background: #3b82f6;
        color: white;
        border-color: #3b82f6;
    }

    .game-info {
        display: flex;
        justify-content: space-between;
        margin-bottom: 1rem;
        font-size: 1.2rem;
        font-weight: 600;
        display: none;
    }

    .sudoku-grid {
        display: grid;
        grid-template-columns: repeat(9, 1fr);
        gap: 0;
        border: 3px solid var(--text-color, #000);
        margin: 0 auto 2rem;
        width: fit-content;
        display: none;
    }

    .sudoku-cell {
        width: 40px;
        height: 40px;
        border: 1px solid var(--border-color);
        display: flex;
        justify-content: center;
        align-items: center;
        font-size: 1.25rem;
        font-weight: 600;
        color: var(--text-color);
    }
    
    .sudoku-cell input {
        width: 100%;
        height: 100%;
        border: none;
        text-align: center;
        font-size: 1.25rem;
        font-weight: 600;
        background: transparent;
        color: #3b82f6;
        outline: none;
    }

    .sudoku-cell input:focus {
        background: rgba(59, 130, 246, 0.1);
    }

    /* Thick borders for 3x3 blocks */
    .sudoku-cell:nth-child(3n) {
        border-right: 3px solid var(--text-color, #000);
    }
    .sudoku-grid .sudoku-cell:nth-child(9n) {
        border-right: none; /* except last column */
    }
    
    .sudoku-cell.sudoku-row-3,
    .sudoku-cell.sudoku-row-6 {
        border-bottom: 3px solid var(--text-color, #000);
    }

    .game-actions {
        display: flex;
        justify-content: center;
        gap: 1rem;
        display: none;
    }

    .btn {
        padding: 0.75rem 1.5rem;
        border-radius: 8px;
        font-weight: 600;
        cursor: pointer;
        border: none;
        transition: opacity 0.2s;
    }

    .btn:hover {
        opacity: 0.9;
    }

    .btn-primary {
        background: #3b82f6;
        color: white;
    }

    .btn-secondary {
        background: var(--card-banner-bg);
        color: var(--text-color);
        border: 1px solid var(--border-color);
    }

    #message {
        margin-top: 1rem;
        font-weight: 600;
        color: #10b981;
        min-height: 24px;
    }
</style>
@endpush

@section('content')
<div class="container mx-auto px-4">
    <div class="mb-4">
        <a href="{{ route('customer.dashboard') }}" class="text-sm" style="color: var(--text-muted); display: inline-flex; align-items: center; gap: 0.25rem;">
            <span>←</span> Back to Dashboard
        </a>
    </div>

    <div class="game-wrapper">
        <div class="sudoku-container game-container">
            <h1 style="font-size: 2rem; font-weight: 700; margin-bottom: 1.5rem;">Sudoku</h1>
            
            <div id="setup-screen">
                <p style="margin-bottom: 1rem; color: var(--text-muted);">Select Difficulty</p>
                <div class="level-selector">
                    <button class="level-btn active" data-level="easy">Easy</button>
                    <button class="level-btn" data-level="medium">Medium</button>
                    <button class="level-btn" data-level="hard">Hard</button>
                </div>
                <button id="start-btn" class="btn btn-primary">Start Game</button>
            </div>

            <div id="game-info" class="game-info">
                <div id="timer">Time: 00:00</div>
                <div id="current-level-display">Easy</div>
                <div id="lives-display">Lives: ❤️❤️❤️</div>
            </div>

            <div id="sudoku-grid" class="sudoku-grid">
                <!-- Cells generated by JS -->
            </div>

            <div id="game-actions" class="game-actions">
                <button id="check-btn" class="btn btn-primary">Submit</button>
                <button id="restart-btn" class="btn btn-secondary">Give Up</button>
            </div>
            
            <div id="message"></div>
        </div>
    </div>
</div>
@endsection

@push('scripts')
<script>
    const setupScreen = document.getElementById('setup-screen');
    const gameInfo = document.getElementById('game-info');
    const sudokuGrid = document.getElementById('sudoku-grid');
    const gameActions = document.getElementById('game-actions');
    const timerDisplay = document.getElementById('timer');
    const livesDisplay = document.getElementById('lives-display');
    const messageDisplay = document.getElementById('message');
    
    let difficulty = 'easy'; // easy (30 missing), medium (40 missing), hard (50 missing)
    let timeElapsed = 0;
    let timerInterval = null;
    let solutionBoard = [];
    let currentBoard = [];
    let lives = 3;

    // Difficulty selection
    document.querySelectorAll('.level-btn').forEach(btn => {
        btn.addEventListener('click', (e) => {
            document.querySelectorAll('.level-btn').forEach(b => b.classList.remove('active'));
            e.target.classList.add('active');
            difficulty = e.target.getAttribute('data-level');
        });
    });

    document.getElementById('start-btn').addEventListener('click', startGame);
    document.getElementById('restart-btn').addEventListener('click', resetGame);
    document.getElementById('check-btn').addEventListener('click', checkWin);

    function startGame() {
        setupScreen.style.display = 'none';
        gameInfo.style.display = 'flex';
        sudokuGrid.style.display = 'grid';
        gameActions.style.display = 'flex';
        document.getElementById('current-level-display').innerText = difficulty.charAt(0).toUpperCase() + difficulty.slice(1);
        
        messageDisplay.innerText = '';
        messageDisplay.style.color = '#10b981';

        generateBoard();
        renderBoard();
        
        timeElapsed = 0;
        lives = 3;
        updateLivesDisplay();
        updateTimerDisplay();
        clearInterval(timerInterval);
        timerInterval = setInterval(() => {
            timeElapsed++;
            updateTimerDisplay();
        }, 1000);
    }

    function resetGame() {
        clearInterval(timerInterval);
        setupScreen.style.display = 'block';
        gameInfo.style.display = 'none';
        sudokuGrid.style.display = 'none';
        gameActions.style.display = 'none';
        messageDisplay.innerText = '';
    }

    function updateTimerDisplay() {
        let mins = Math.floor(timeElapsed / 60).toString().padStart(2, '0');
        let secs = (timeElapsed % 60).toString().padStart(2, '0');
        timerDisplay.innerText = `Time: ${mins}:${secs}`;
    }

    function updateLivesDisplay() {
        livesDisplay.innerText = `Lives: ${'❤️'.repeat(lives)}`;
    }

    function gameOver() {
        clearInterval(timerInterval);
        messageDisplay.innerText = 'Game Over! You ran out of lives.';
        messageDisplay.style.color = '#ef4444';
        
        // Disable all inputs
        document.querySelectorAll('.sudoku-cell input').forEach(input => {
            input.disabled = true;
        });
        
        document.getElementById('check-btn').style.display = 'none';
        document.getElementById('restart-btn').innerText = 'Try Again';
    }

    // Sudoku Generator Algorithm
    function generateBoard() {
        // 1. Create empty 9x9 board
        solutionBoard = Array.from({length: 9}, () => Array(9).fill(0));
        
        // 2. Fill diagonal 3x3 boxes (they are independent)
        for(let i = 0; i < 9; i += 3) {
            fillBox(i, i);
        }
        
        // 3. Solve the rest of the board to get a valid solution
        solveSudoku(solutionBoard);
        
        // 4. Remove elements based on difficulty
        currentBoard = JSON.parse(JSON.stringify(solutionBoard)); // Deep copy
        
        let missingCount = 30;
        if (difficulty === 'medium') missingCount = 45;
        if (difficulty === 'hard') missingCount = 55;
        
        let removed = 0;
        while(removed < missingCount) {
            let r = Math.floor(Math.random() * 9);
            let c = Math.floor(Math.random() * 9);
            if(currentBoard[r][c] !== 0) {
                currentBoard[r][c] = 0;
                removed++;
            }
        }
    }

    function fillBox(rowStart, colStart) {
        let num;
        for (let i = 0; i < 3; i++) {
            for (let j = 0; j < 3; j++) {
                do {
                    num = Math.floor(Math.random() * 9) + 1;
                } while (!isSafeInBox(rowStart, colStart, num));
                solutionBoard[rowStart + i][colStart + j] = num;
            }
        }
    }

    function isSafeInBox(rowStart, colStart, num) {
        for (let i = 0; i < 3; i++) {
            for (let j = 0; j < 3; j++) {
                if (solutionBoard[rowStart + i][colStart + j] === num) return false;
            }
        }
        return true;
    }

    function solveSudoku(board) {
        for (let row = 0; row < 9; row++) {
            for (let col = 0; col < 9; col++) {
                if (board[row][col] === 0) {
                    for (let num = 1; num <= 9; num++) {
                        if (isSafe(board, row, col, num)) {
                            board[row][col] = num;
                            if (solveSudoku(board)) return true;
                            board[row][col] = 0;
                        }
                    }
                    return false;
                }
            }
        }
        return true;
    }

    function isSafe(board, row, col, num) {
        for (let x = 0; x < 9; x++) {
            if (board[row][x] === num || board[x][col] === num) return false;
        }
        let startRow = row - row % 3, startCol = col - col % 3;
        for (let i = 0; i < 3; i++) {
            for (let j = 0; j < 3; j++) {
                if (board[i + startRow][j + startCol] === num) return false;
            }
        }
        return true;
    }

    function renderBoard() {
        sudokuGrid.innerHTML = '';
        for (let i = 0; i < 9; i++) {
            // Group rows for styling
            let rowClass = '';
            if (i === 2) rowClass = 'sudoku-row-3';
            if (i === 5) rowClass = 'sudoku-row-6';
            
            for (let j = 0; j < 9; j++) {
                let cell = document.createElement('div');
                cell.className = `sudoku-cell ${rowClass}`;
                
                let val = currentBoard[i][j];
                if (val !== 0) {
                    cell.innerText = val;
                } else {
                    let input = document.createElement('input');
                    input.type = 'text';
                    input.maxLength = 1;
                    input.dataset.row = i;
                    input.dataset.col = j;
                    input.addEventListener('input', (e) => {
                        let v = e.target.value;
                        if (!/^[1-9]$/.test(v)) {
                            e.target.value = '';
                            e.target.style.color = '#3b82f6';
                            return;
                        }
                        
                        // Check if correct immediately
                        let r = parseInt(e.target.dataset.row);
                        let c = parseInt(e.target.dataset.col);
                        if (parseInt(v) !== solutionBoard[r][c]) {
                            e.target.style.color = '#ef4444';
                            lives--;
                            updateLivesDisplay();
                            if (lives <= 0) {
                                gameOver();
                            }
                        } else {
                            e.target.style.color = '#10b981'; // Green for correct
                            e.target.disabled = true; // Lock it in
                        }
                    });
                    cell.appendChild(input);
                }
                sudokuGrid.appendChild(cell);
            }
        }
    }

    function checkWin() {
        let isComplete = true;
        let isCorrect = true;
        let inputs = document.querySelectorAll('.sudoku-cell input');
        
        inputs.forEach(input => {
            let r = parseInt(input.dataset.row);
            let c = parseInt(input.dataset.col);
            let val = input.value;
            
            if (val === '') {
                isComplete = false;
            } else if (parseInt(val) !== solutionBoard[r][c]) {
                isCorrect = false;
                input.style.color = '#ef4444'; // mark red if wrong
            } else {
                input.style.color = '#3b82f6'; // correct
            }
        });

        if (!isComplete) {
            messageDisplay.innerText = 'Please fill all cells!';
            messageDisplay.style.color = '#f59e0b';
        } else if (!isCorrect) {
            messageDisplay.innerText = 'Some numbers are incorrect!';
            messageDisplay.style.color = '#ef4444';
        } else {
            // Victory
            clearInterval(timerInterval);
            messageDisplay.innerText = `Puzzle Solved in ${timeElapsed} seconds!`;
            messageDisplay.style.color = '#10b981';
            document.getElementById('check-btn').style.display = 'none';
            document.getElementById('restart-btn').innerText = 'Play Again';
            
            // Submit time as score (lower is better for Sudoku/MemoryMatch)
            fetch('{{ route('customer.game-scores.store') }}', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRF-TOKEN': '{{ csrf_token() }}',
                    'Accept': 'application/json'
                },
                body: JSON.stringify({
                    game_type: 'sudoku',
                    score: timeElapsed
                })
            }).catch(console.error);
        }
    }
</script>
@endpush
