@extends('layouts.app')

@section('title', 'Memory Match')

@push('styles')
<style>
    .game-container {
        max-width: 600px;
        margin: 0 auto;
        text-align: center;
        font-family: var(--font-sans, system-ui, sans-serif);
        padding: 2rem 0 1rem;
    }

    .stats {
        display: flex;
        justify-content: space-between;
        margin-bottom: 2rem;
        font-size: 1.0625rem;
        font-weight: 500;
        color: var(--text-color, #111);
        background: var(--card-bg, #fff);
        padding: 1rem 1.5rem;
        border-radius: 12px;
        border: 0.5px solid var(--border-color);
    }

    .memory-grid {
        display: grid;
        grid-template-columns: repeat(4, 1fr);
        gap: 1rem;
        perspective: 1000px;
    }

    .memory-card {
        aspect-ratio: 1;
        position: relative;
        transform-style: preserve-3d;
        transition: transform 0.5s cubic-bezier(0.4, 0, 0.2, 1);
        cursor: pointer;
    }

    .memory-card.flip {
        transform: rotateY(180deg);
    }

    .front-face, .back-face {
        width: 100%;
        height: 100%;
        position: absolute;
        backface-visibility: hidden;
        display: flex;
        align-items: center;
        justify-content: center;
        border-radius: 12px;
        font-size: 2.5rem;
        border: 0.5px solid var(--border-color);
    }

    .front-face {
        background: var(--card-bg, #fff);
        transform: rotateY(180deg);
    }

    .back-face {
        background: var(--card-banner-bg, #f8f8f9);
        color: var(--text-muted);
        font-size: 2rem;
    }

    .win-message {
        display: none;
        margin-top: 2rem;
        animation: slideUp 0.5s ease;
        background: var(--card-bg, #fff);
        border: 0.5px solid var(--border-color);
        padding: 2rem;
        border-radius: 16px;
    }

    .win-message h2 {
        font-size: 2rem;
        font-weight: 500;
        color: var(--text-color, #111);
        margin-bottom: 0.5rem;
    }

    .win-message p {
        color: var(--text-muted);
        margin-bottom: 1.5rem;
    }

    .controls {
        margin-top: 2.5rem;
        display: flex;
        justify-content: center;
        gap: 1rem;
        flex-wrap: wrap;
    }
</style>
@endpush

@section('content')
<div class="game-container">
    <div style="text-align: center; margin-bottom: 2rem;">
        <p style="font-size: 11px; letter-spacing: 0.12em; text-transform: uppercase; color: var(--text-muted); margin: 0 0 0.75rem;">Memory</p>
        <h1 style="font-size: 2rem; font-weight: 500; color: var(--text-color, #111); margin: 0 0 0.4rem; line-height: 1.2;">Memory Match</h1>
        <p style="font-size: 0.9375rem; color: var(--text-muted); margin: 0;">Find all the matching pairs!</p>
    </div>

    <div class="stats">
        <div>Moves: <span id="moves" style="color: var(--primary);">0</span></div>
        <div>Time: <span id="time" style="color: var(--primary);">0</span>s</div>
    </div>

    <div class="memory-grid" id="grid">
        <!-- Cards generated by JS -->
    </div>

    <div class="win-message" id="win-message">
        <h2>🎉 You Won!</h2>
        <p>You completed the game in <strong id="final-moves"></strong> moves and <strong id="final-time"></strong> seconds.</p>
        <button class="btn" onclick="initGame()">Play Again</button>
    </div>

    <div class="controls">
        <button class="btn btn-secondary" onclick="initGame()">Restart Game</button>
        <a href="{{ route('customer.leaderboards.game', 'memory_match') }}" class="btn btn-secondary">Leaderboard</a>
        <a href="{{ route('customer.dashboard') }}" class="btn btn-secondary">Back</a>
    </div>
</div>
@endsection

@push('scripts')
<script>
    const emojis = ['🐶', '🐱', '🐭', '🐹', '🐰', '🦊', '🐻', '🐼'];
    let cards = [];
    let hasFlippedCard = false;
    let lockBoard = false;
    let firstCard, secondCard;
    let moves = 0;
    let matches = 0;
    let timer;
    let seconds = 0;
    let gameStarted = false;

    const grid = document.getElementById('grid');
    const movesEl = document.getElementById('moves');
    const timeEl = document.getElementById('time');
    const winMessage = document.getElementById('win-message');
    const finalMoves = document.getElementById('final-moves');
    const finalTime = document.getElementById('final-time');

    function initGame() {
        grid.innerHTML = '';
        winMessage.style.display = 'none';
        moves = 0;
        matches = 0;
        seconds = 0;
        hasFlippedCard = false;
        lockBoard = false;
        firstCard = null;
        secondCard = null;
        gameStarted = false;
        clearInterval(timer);
        movesEl.innerText = moves;
        timeEl.innerText = seconds;

        // Duplicate and shuffle array
        cards = [...emojis, ...emojis];
        cards.sort(() => Math.random() - 0.5);

        cards.forEach((emoji) => {
            const card = document.createElement('div');
            card.classList.add('memory-card');
            card.dataset.framework = emoji;

            card.innerHTML = `
                <div class="front-face">${emoji}</div>
                <div class="back-face">❓</div>
            `;

            card.addEventListener('click', flipCard);
            grid.appendChild(card);
        });
    }

    function startTimer() {
        if (gameStarted) return;
        gameStarted = true;
        timer = setInterval(() => {
            seconds++;
            timeEl.innerText = seconds;
        }, 1000);
    }

    function flipCard() {
        if (lockBoard) return;
        if (this === firstCard) return;

        startTimer();

        this.classList.add('flip');

        if (!hasFlippedCard) {
            hasFlippedCard = true;
            firstCard = this;
            return;
        }

        secondCard = this;
        moves++;
        movesEl.innerText = moves;
        checkForMatch();
    }

    function checkForMatch() {
        let isMatch = firstCard.dataset.framework === secondCard.dataset.framework;

        if (isMatch) {
            disableCards();
            matches++;
            if (matches === emojis.length) {
                setTimeout(winGame, 500);
            }
        } else {
            unflipCards();
        }
    }

    function disableCards() {
        firstCard.removeEventListener('click', flipCard);
        secondCard.removeEventListener('click', flipCard);
        resetBoard();
    }

    function unflipCards() {
        lockBoard = true;
        setTimeout(() => {
            firstCard.classList.remove('flip');
            secondCard.classList.remove('flip');
            resetBoard();
        }, 1000);
    }

    function resetBoard() {
        [hasFlippedCard, lockBoard] = [false, false];
        [firstCard, secondCard] = [null, null];
    }

    function winGame() {
        clearInterval(timer);
        finalMoves.innerText = moves;
        finalTime.innerText = seconds;
        winMessage.style.display = 'block';

        // Submit score to database
        fetch("{{ route('customer.game-scores.store') }}", {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'X-CSRF-TOKEN': '{{ csrf_token() }}'
            },
            body: JSON.stringify({ game_type: 'memory_match', score: seconds })
        });
    }

    // Initialize the game on load
    document.addEventListener('DOMContentLoaded', initGame);
</script>
@endpush
